# Curated OUI lookup for network device identification
# Format: "xx:xx:xx" (lowercase) -> (vendor, device_type)

OUI_DB = {
    # === DVR / Security Cameras ===
    "34:ea:34": ("Hikvision", "DVR/Camera"),
    "bc:ad:28": ("Hikvision", "DVR/Camera"),
    "c0:56:e3": ("Hikvision", "DVR/Camera"),
    "44:19:b6": ("Hikvision", "DVR/Camera"),
    "8c:e7:48": ("Hikvision", "DVR/Camera"),
    "e8:b4:c8": ("Hikvision", "DVR/Camera"),
    "54:c4:15": ("Hikvision", "DVR/Camera"),
    "a4:14:37": ("Hikvision", "DVR/Camera"),
    "28:57:be": ("Hikvision", "DVR/Camera"),
    "4c:bd:8f": ("Hikvision", "DVR/Camera"),
    "d4:e9:8a": ("Hikvision", "DVR/Camera"),
    "c4:2f:90": ("Hikvision", "DVR/Camera"),
    "90:02:a9": ("Dahua Technology", "DVR/Camera"),
    "70:85:c2": ("Dahua Technology", "DVR/Camera"),
    "b4:a3:82": ("Dahua Technology", "DVR/Camera"),
    "3c:ef:8c": ("Dahua Technology", "DVR/Camera"),
    "e0:50:8b": ("Dahua Technology", "DVR/Camera"),
    "08:ed:ed": ("Dahua Technology", "DVR/Camera"),
    "00:40:8c": ("Axis Communications", "IP Camera"),
    "ac:cc:8e": ("Axis Communications", "IP Camera"),
    "b8:a4:4f": ("Axis Communications", "IP Camera"),
    "00:60:51": ("Bosch Security", "IP Camera"),
    "00:07:70": ("Bosch Security", "DVR/Camera"),
    "8c:79:f0": ("FLIR Systems", "IP Camera"),
    "00:02:d1": ("Vivotek", "IP Camera"),
    "ec:71:db": ("Reolink", "IP Camera"),
    "74:ae:f2": ("Reolink", "IP Camera"),
    "9c:8e:cd": ("Amcrest", "IP Camera"),
    "48:ea:63": ("Uniview", "DVR/Camera"),
    "c0:39:37": ("Uniview", "DVR/Camera"),
    "bc:e2:43": ("Hanwha/Samsung Techwin", "DVR/Camera"),
    "00:09:18": ("Hanwha/Samsung Techwin", "DVR/Camera"),
    "78:45:61": ("Hanwha/Samsung Techwin", "DVR/Camera"),

    # === Routers / Access Points ===
    "00:00:0c": ("Cisco", "Router"),
    "00:1a:2f": ("Cisco", "Router"),
    "00:0e:83": ("Cisco", "Router"),
    "00:1b:8f": ("Cisco", "Router"),
    "88:75:56": ("Cisco", "Router"),
    "f8:7b:20": ("Cisco", "Router"),
    "00:15:6d": ("Ubiquiti", "AP"),
    "04:18:d6": ("Ubiquiti", "AP"),
    "44:d9:e7": ("Ubiquiti", "AP"),
    "68:72:51": ("Ubiquiti", "AP"),
    "78:8a:20": ("Ubiquiti", "AP"),
    "80:2a:a8": ("Ubiquiti", "AP"),
    "b4:fb:e4": ("Ubiquiti", "AP"),
    "dc:9f:db": ("Ubiquiti", "AP"),
    "e0:63:da": ("Ubiquiti", "AP"),
    "f4:92:bf": ("Ubiquiti", "AP"),
    "24:a4:3c": ("Ubiquiti", "AP"),
    "18:e8:29": ("Ubiquiti", "AP"),
    "00:09:5b": ("Netgear", "Router"),
    "00:14:6c": ("Netgear", "Router"),
    "20:4e:7f": ("Netgear", "Router"),
    "2c:30:33": ("Netgear", "Router"),
    "a0:21:b7": ("Netgear", "Router"),
    "c0:ff:d4": ("Netgear", "Router"),
    "14:cc:20": ("TP-Link", "Router"),
    "50:c7:bf": ("TP-Link", "Router"),
    "54:af:97": ("TP-Link", "Router"),
    "74:da:38": ("TP-Link", "Router"),
    "98:da:c4": ("TP-Link", "Router"),
    "c4:e9:84": ("TP-Link", "Router"),
    "ec:08:6b": ("TP-Link", "Router"),
    "f4:f2:6d": ("TP-Link", "Router"),
    "30:de:4b": ("TP-Link", "Router"),
    "00:0f:3d": ("D-Link", "Router"),
    "00:1c:f0": ("D-Link", "Router"),
    "1c:7e:e5": ("D-Link", "Router"),
    "90:94:e4": ("D-Link", "Router"),
    "b8:a3:86": ("D-Link", "Router"),
    "00:1a:92": ("ASUS", "Router"),
    "04:d4:c4": ("ASUS", "Router"),
    "2c:4d:54": ("ASUS", "Router"),
    "50:46:5d": ("ASUS", "Router"),
    "6c:19:8f": ("ASUS", "Router"),
    "90:e6:ba": ("ASUS", "Router"),
    "ac:22:0b": ("ASUS", "Router"),
    "00:12:17": ("Linksys", "Router"),
    "00:14:bf": ("Linksys", "Router"),
    "20:aa:4b": ("Linksys", "Router"),
    "c0:56:27": ("Linksys", "Router"),
    "00:0c:42": ("MikroTik", "Router"),
    "18:fd:74": ("MikroTik", "Router"),
    "2c:c8:1b": ("MikroTik", "Router"),
    "48:8f:5a": ("MikroTik", "Router"),
    "64:d1:54": ("MikroTik", "Router"),
    "b8:69:f4": ("MikroTik", "Router"),
    "cc:2d:e0": ("MikroTik", "Router"),
    "d4:ca:6d": ("MikroTik", "Router"),
    "e4:8d:8c": ("MikroTik", "Router"),
    "4c:5e:0c": ("MikroTik", "Router"),
    "00:18:82": ("Huawei", "Router"),
    "04:02:1f": ("Huawei", "Router"),
    "2c:ab:00": ("Huawei", "Router"),
    "48:46:fb": ("Huawei", "Router"),
    "5c:43:bc": ("Huawei", "Router"),
    "a4:99:47": ("Huawei", "Router"),
    "d4:a1:48": ("Huawei", "Router"),
    "00:26:ed": ("ZTE", "Router"),
    "4c:09:b4": ("ZTE", "Router"),
    "7c:b7:33": ("ZTE", "Router"),
    "00:0b:86": ("Aruba/HP", "AP"),
    "00:24:6c": ("Aruba/HP", "AP"),
    "94:b4:0f": ("Aruba/HP", "AP"),
    "d8:c7:c8": ("Aruba/HP", "AP"),
    "00:22:7f": ("Ruckus", "AP"),
    "24:c9:a1": ("Ruckus", "AP"),
    "84:18:3a": ("Ruckus", "AP"),
    "c8:3a:35": ("Tenda", "Router"),
    "00:e0:4c": ("Tenda", "Router"),
    "26:b8:c8": ("Peplink", "Router"),

    # === Apple ===
    "04:0c:ce": ("Apple", "iPhone/iPad"),
    "04:26:65": ("Apple", "iPhone/iPad"),
    "04:52:f3": ("Apple", "iPhone/iPad"),
    "04:d3:cf": ("Apple", "iPhone/iPad"),
    "08:66:98": ("Apple", "iPhone/iPad"),
    "0c:74:c2": ("Apple", "iPhone/iPad"),
    "10:1c:0c": ("Apple", "iPhone/iPad"),
    "18:20:32": ("Apple", "iPhone/iPad"),
    "18:65:90": ("Apple", "iPhone/iPad"),
    "18:81:0e": ("Apple", "iPhone/iPad"),
    "1c:1a:c0": ("Apple", "iPhone/iPad"),
    "20:78:f0": ("Apple", "iPhone/iPad"),
    "28:6a:b8": ("Apple", "iPhone/iPad"),
    "28:a0:2b": ("Apple", "iPhone/iPad"),
    "2c:be:08": ("Apple", "iPhone/iPad"),
    "34:08:bc": ("Apple", "iPhone/iPad"),
    "38:b5:4d": ("Apple", "iPhone/iPad"),
    "3c:07:54": ("Apple", "iPhone/iPad"),
    "40:3c:fc": ("Apple", "iPhone/iPad"),
    "44:00:10": ("Apple", "iPhone/iPad"),
    "48:bf:6b": ("Apple", "iPhone/iPad"),
    "4c:57:ca": ("Apple", "iPhone/iPad"),
    "50:ea:d6": ("Apple", "iPhone/iPad"),
    "54:4e:90": ("Apple", "iPhone/iPad"),
    "58:1f:aa": ("Apple", "iPhone/iPad"),
    "5c:8d:4e": ("Apple", "iPhone/iPad"),
    "60:03:08": ("Apple", "iPhone/iPad"),
    "60:69:44": ("Apple", "iPhone/iPad"),
    "64:9a:be": ("Apple", "iPhone/iPad"),
    "68:96:7b": ("Apple", "iPhone/iPad"),
    "6c:40:08": ("Apple", "iPhone/iPad"),
    "70:56:81": ("Apple", "iPhone/iPad"),
    "70:73:cb": ("Apple", "iPhone/iPad"),
    "74:e2:f5": ("Apple", "iPhone/iPad"),
    "7c:6d:62": ("Apple", "iPhone/iPad"),
    "80:49:71": ("Apple", "iPhone/iPad"),
    "84:38:35": ("Apple", "iPhone/iPad"),
    "84:a1:34": ("Apple", "iPhone/iPad"),
    "88:66:a5": ("Apple", "iPhone/iPad"),
    "90:27:e4": ("Apple", "iPhone/iPad"),
    "94:94:26": ("Apple", "iPhone/iPad"),
    "94:bf:c4": ("Apple", "iPhone/iPad"),
    "98:5a:eb": ("Apple", "iPhone/iPad"),
    "9c:04:eb": ("Apple", "iPhone/iPad"),
    "a0:99:9b": ("Apple", "iPhone/iPad"),
    "a4:b1:97": ("Apple", "iPhone/iPad"),
    "a8:51:5b": ("Apple", "iPhone/iPad"),
    "a8:60:b6": ("Apple", "iPhone/iPad"),
    "ac:3c:0b": ("Apple", "iPhone/iPad"),
    "ac:bc:32": ("Apple", "iPhone/iPad"),
    "b0:34:95": ("Apple", "iPhone/iPad"),
    "b4:18:d1": ("Apple", "iPhone/iPad"),
    "b8:09:8a": ("Apple", "iPhone/iPad"),
    "bc:52:b7": ("Apple", "iPhone/iPad"),
    "c0:ce:cd": ("Apple", "iPhone/iPad"),
    "c4:b3:01": ("Apple", "iPhone/iPad"),
    "c8:2a:14": ("Apple", "iPhone/iPad"),
    "c8:d0:83": ("Apple", "iPhone/iPad"),
    "cc:29:f5": ("Apple", "iPhone/iPad"),
    "d0:23:db": ("Apple", "iPhone/iPad"),
    "d4:90:9c": ("Apple", "iPhone/iPad"),
    "d8:00:4d": ("Apple", "iPhone/iPad"),
    "d8:1d:72": ("Apple", "iPhone/iPad"),
    "dc:2b:61": ("Apple", "iPhone/iPad"),
    "dc:9b:9c": ("Apple", "iPhone/iPad"),
    "e0:b9:ba": ("Apple", "iPhone/iPad"),
    "e4:ce:8f": ("Apple", "iPhone/iPad"),
    "e8:8d:28": ("Apple", "iPhone/iPad"),
    "ec:35:86": ("Apple", "iPhone/iPad"),
    "f0:db:e2": ("Apple", "iPhone/iPad"),
    "f4:31:c3": ("Apple", "iPhone/iPad"),
    "f4:f1:5a": ("Apple", "iPhone/iPad"),
    "f8:62:14": ("Apple", "iPhone/iPad"),
    "fc:25:3f": ("Apple", "iPhone/iPad"),

    # === Samsung ===
    "00:12:47": ("Samsung", "Android Device"),
    "08:08:c2": ("Samsung", "Android Device"),
    "0c:14:20": ("Samsung", "Android Device"),
    "14:32:d1": ("Samsung", "Android Device"),
    "18:22:7e": ("Samsung", "Android Device"),
    "20:13:e0": ("Samsung", "Android Device"),
    "24:4b:81": ("Samsung", "Android Device"),
    "28:ba:b5": ("Samsung", "Android Device"),
    "2c:0e:3d": ("Samsung", "Android Device"),
    "34:23:87": ("Samsung", "Android Device"),
    "38:2d:e8": ("Samsung", "Android Device"),
    "40:0e:85": ("Samsung", "Android Device"),
    "44:6d:57": ("Samsung", "Android Device"),
    "48:44:f7": ("Samsung", "Android Device"),
    "4c:a5:15": ("Samsung", "Android Device"),
    "50:01:bb": ("Samsung", "Android Device"),
    "54:88:0e": ("Samsung", "Android Device"),
    "58:ef:68": ("Samsung", "Android Device"),
    "5c:49:79": ("Samsung", "Android Device"),
    "64:b3:10": ("Samsung", "Android Device"),
    "68:eb:ae": ("Samsung", "Android Device"),
    "6c:f3:73": ("Samsung", "Android Device"),
    "70:f9:27": ("Samsung", "Android Device"),
    "78:1f:db": ("Samsung", "Android Device"),
    "7c:64:56": ("Samsung", "Android Device"),
    "80:65:6d": ("Samsung", "Android Device"),
    "84:55:a5": ("Samsung", "Android Device"),
    "88:32:9b": ("Samsung", "Android Device"),
    "8c:77:12": ("Samsung", "Android Device"),
    "90:18:7c": ("Samsung", "Android Device"),
    "94:35:0a": ("Samsung", "Android Device"),
    "98:52:b1": ("Samsung", "Android Device"),
    "9c:3a:af": ("Samsung", "Android Device"),
    "a0:0b:ba": ("Samsung", "Android Device"),
    "a4:eb:d3": ("Samsung", "Android Device"),
    "a8:9f:ec": ("Samsung", "Android Device"),
    "b0:c5:59": ("Samsung", "Android Device"),
    "b4:3a:28": ("Samsung", "Android Device"),
    "bc:14:ef": ("Samsung", "Android Device"),
    "c0:bd:d1": ("Samsung", "Android Device"),
    "c4:42:02": ("Samsung", "Android Device"),
    "cc:f9:54": ("Samsung", "Android Device"),
    "d0:17:6a": ("Samsung", "Android Device"),
    "d4:87:d8": ("Samsung", "Android Device"),
    "d8:57:ef": ("Samsung", "Android Device"),
    "dc:71:96": ("Samsung", "Android Device"),
    "e0:99:71": ("Samsung", "Android Device"),
    "e4:92:fb": ("Samsung", "Android Device"),
    "e8:4e:84": ("Samsung", "Android Device"),
    "ec:1f:72": ("Samsung", "Android Device"),
    "f0:25:b7": ("Samsung", "Android Device"),
    "f4:7b:5e": ("Samsung", "Android Device"),
    "fc:a1:3e": ("Samsung", "Android Device"),

    # === Xiaomi ===
    "00:9e:c8": ("Xiaomi", "Android Device"),
    "04:cf:8c": ("Xiaomi", "Android Device"),
    "14:f6:5a": ("Xiaomi", "Android Device"),
    "18:59:36": ("Xiaomi", "Android Device"),
    "28:6c:07": ("Xiaomi", "Android Device"),
    "34:80:b3": ("Xiaomi", "Android Device"),
    "38:a4:ed": ("Xiaomi", "Android Device"),
    "40:31:3c": ("Xiaomi", "Android Device"),
    "58:44:98": ("Xiaomi", "Android Device"),
    "5c:e8:eb": ("Xiaomi", "Android Device"),
    "64:09:80": ("Xiaomi", "Android Device"),
    "68:df:dd": ("Xiaomi", "Android Device"),
    "74:51:ba": ("Xiaomi", "Android Device"),
    "8c:be:be": ("Xiaomi", "Android Device"),
    "94:fb:b2": ("Xiaomi", "Android Device"),
    "9c:99:a0": ("Xiaomi", "Android Device"),
    "a0:86:c6": ("Xiaomi", "Android Device"),
    "ac:c1:ee": ("Xiaomi", "Android Device"),
    "b0:e2:35": ("Xiaomi", "Android Device"),
    "c4:0b:cb": ("Xiaomi", "Android Device"),
    "c8:47:8c": ("Xiaomi", "Android Device"),
    "f4:8b:32": ("Xiaomi", "Android Device"),
    "f8:a2:d6": ("Xiaomi", "Android Device"),

    # === Huawei Phones ===
    "28:6e:d4": ("Huawei", "Android Device"),
    "38:37:8b": ("Huawei", "Android Device"),
    "40:4d:7f": ("Huawei", "Android Device"),
    "54:89:98": ("Huawei", "Android Device"),
    "58:2a:f7": ("Huawei", "Android Device"),
    "68:cc:6e": ("Huawei", "Android Device"),
    "78:d6:f0": ("Huawei", "Android Device"),
    "84:a8:e4": ("Huawei", "Android Device"),
    "8c:34:fd": ("Huawei", "Android Device"),
    "94:04:9c": ("Huawei", "Android Device"),
    "98:f1:70": ("Huawei", "Android Device"),
    "a8:16:d0": ("Huawei", "Android Device"),
    "b4:86:55": ("Huawei", "Android Device"),
    "c8:14:79": ("Huawei", "Android Device"),
    "cc:b8:c9": ("Huawei", "Android Device"),
    "d8:49:0b": ("Huawei", "Android Device"),
    "e8:4d:d0": ("Huawei", "Android Device"),
    "f4:cb:52": ("Huawei", "Android Device"),

    # === Computers ===
    "00:14:22": ("Dell", "Computer"),
    "00:21:70": ("Dell", "Computer"),
    "18:03:73": ("Dell", "Computer"),
    "24:b6:fd": ("Dell", "Computer"),
    "3c:2c:30": ("Dell", "Computer"),
    "b8:ca:3a": ("Dell", "Computer"),
    "f8:db:88": ("Dell", "Computer"),
    "00:0f:20": ("HP", "Computer"),
    "00:17:08": ("HP", "Computer"),
    "3c:d9:2b": ("HP", "Computer"),
    "b4:99:ba": ("HP", "Computer"),
    "d8:d3:85": ("HP", "Computer"),
    "f8:b1:56": ("HP", "Computer"),
    "00:21:cc": ("Lenovo", "Computer"),
    "0c:8b:fd": ("Lenovo", "Computer"),
    "28:d2:44": ("Lenovo", "Computer"),
    "3c:97:0e": ("Lenovo", "Computer"),
    "54:ee:75": ("Lenovo", "Computer"),
    "8c:73:6e": ("Lenovo", "Computer"),
    "a4:4c:c8": ("Lenovo", "Computer"),
    "e8:6a:64": ("Lenovo", "Computer"),
    "00:02:b3": ("Intel", "Computer"),
    "00:0e:35": ("Intel", "Computer"),
    "00:23:14": ("Intel", "Computer"),
    "40:25:c2": ("Intel", "Computer"),
    "5c:51:4f": ("Intel", "Computer"),
    "68:05:ca": ("Intel", "Computer"),
    "8c:8d:28": ("Intel", "Computer"),
    "a4:34:d9": ("Intel", "Computer"),
    "b0:a7:32": ("Intel", "Computer"),
    "dc:fb:48": ("Intel", "Computer"),

    # === Smart Home / IoT ===
    "38:f7:3d": ("Amazon Echo", "Smart Speaker"),
    "40:b4:cd": ("Amazon Echo", "Smart Speaker"),
    "44:65:0d": ("Amazon Echo", "Smart Speaker"),
    "74:c2:46": ("Amazon Echo", "Smart Speaker"),
    "a0:02:dc": ("Amazon Echo", "Smart Speaker"),
    "b4:7c:9c": ("Amazon Echo", "Smart Speaker"),
    "f0:81:73": ("Amazon Echo", "Smart Speaker"),
    "68:37:e9": ("Amazon Fire TV", "Streaming Device"),
    "18:b4:30": ("Google Nest", "Smart Home"),
    "20:df:b9": ("Google Nest", "Smart Home"),
    "48:d6:d5": ("Google Chromecast", "Streaming Device"),
    "54:60:09": ("Google Nest", "Smart Home"),
    "6c:ad:f8": ("Google Chromecast", "Streaming Device"),
    "7c:2e:bd": ("Google Nest", "Smart Home"),
    "f4:f5:d8": ("Google Nest", "Smart Home"),
    "00:17:88": ("Philips Hue", "Smart Light"),
    "ec:b5:fa": ("Philips Hue", "Smart Light"),
    "b8:27:eb": ("Raspberry Pi", "IoT Device"),
    "dc:a6:32": ("Raspberry Pi", "IoT Device"),
    "e4:5f:01": ("Raspberry Pi", "IoT Device"),
    "00:0e:58": ("Sonos", "Smart Speaker"),
    "34:7e:5c": ("Sonos", "Smart Speaker"),
    "78:28:ca": ("Sonos", "Smart Speaker"),
    "94:9f:3e": ("Sonos", "Smart Speaker"),
    "b8:e9:37": ("Sonos", "Smart Speaker"),
    "54:42:49": ("Sony PlayStation", "Gaming Console"),
    "98:b6:e9": ("Nintendo Switch", "Gaming Console"),
    "a4:c0:e1": ("Nintendo Switch", "Gaming Console"),
    "00:13:a9": ("Sony", "Device"),
    "10:4f:a8": ("Sony", "Device"),
    "30:17:aa": ("Sony", "Device"),
    "a8:23:fe": ("LG", "Smart TV"),
    "b8:ad:3e": ("LG", "Smart TV"),
    "00:12:fb": ("Samsung", "Smart TV"),
}


def get_oui(mac: str) -> tuple:
    if not mac or len(mac) < 8:
        return ("Unknown", "Unknown Device")
    mac_lower = mac.lower().replace('-', ':')
    # Normalize to xx:xx:xx:xx:xx:xx if needed
    parts = mac_lower.split(':')
    if len(parts) < 3:
        return ("Unknown", "Unknown Device")
    prefix = ':'.join(parts[:3])
    return OUI_DB.get(prefix, ("Unknown", "Unknown Device"))


def get_vendor(mac: str) -> str:
    return get_oui(mac)[0]


def get_device_type(mac: str) -> str:
    return get_oui(mac)[1]
